[project]
name = "aidial-interceptors-sdk"
version = "0.0.0"
description = "Framework for creating interceptors for AI DIAL"
authors = [{ name = "EPAM RAIL", email = "SpecialEPM-DIALDevTeam@epam.com" }]
license = "Apache-2.0"
readme = "README.md"
keywords = ["ai"]
classifiers = ["Topic :: Software Development :: Libraries :: Python Modules"]
requires-python = ">=3.11,<3.13"
dependencies = [
    "fastapi (>=0.51,<1.0)",
    "httpx (>=0.25.0,<1.0)",
    "openai (>=1.32.0,<2.0)",
    "aidial-sdk[telemetry] (>=0.21.0)",
]

[project.urls]
Homepage = "https://epam-rail.com"
Documentation = "https://epam-rail.com/dial_api"
Repository = "https://github.com/epam/ai-dial-interceptors-sdk"

[project.scripts]
clean = "scripts.clean:main"
codegen = "scripts.codegen:main"

[project.optional-dependencies]
examples = [
    "aiostream (==0.6.2)",
    "pillow (==12.2.0)",
    "numpy (==1.26.4)",
    "spacy (==3.8.14)",
    "langfuse (==2.60.2)",
    "protobuf (==6.33.5)",
    "google-cloud-dlp (==3.30.0)",
]

[tool.poetry.group.test.dependencies]
pytest = "9.0.3"
pytest-asyncio = "1.3.0"
pytest-dotenv = "0.5.2"
python-dotenv = "1.2.2"
numpy = "1.26.4"

[tool.poetry.group.lint.dependencies]
pyright = "1.1.324"
ruff = "0.12.11"

[tool.poetry.group.dev.dependencies]
nox = "2023.4.22"
pre-commit = "^4.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--asyncio-mode=auto --doctest-modules"
testpaths = ["tests", "aidial_interceptors_sdk.examples"]
filterwarnings = [
    # muting warnings coming from opentelemetry package
    "ignore::DeprecationWarning:opentelemetry.instrumentation.dependencies",
]

[tool.pyright]
typeCheckingMode = "basic"
reportUnusedVariable = "error"
reportIncompatibleMethodOverride = "error"

[tool.ruff]
target-version = "py311"
line-length = 80

[tool.ruff.lint]
select = [
    "ERA",  # flake8-eradicate
    "B",    # flake8-builtins
    "C4",   # flake8-comprehensions
    "SIM",  # flake8-simplify
    "B9",   # flake8-bugbear
    "E",    # pycodestyle
    "W",    # pycodestyle
    "F",    # pyflakes
    "I",    # flake8-isort
    "S",    # flake8-bandit
    "FURB", # refurb
    "UP",   #  pyupgrade
]
ignore = [
    "E501", # string literal is too long
    "S101", # Use of `assert` detected
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "B011", # Do not `assert False`
    "B006", # Do not use mutable data structures for argument defaults
    "B008", # Do not perform function call in argument defaults
]
