[tool.poetry]
name = "ai-dial-interceptors-langfuse"
version = "1.0.17"
description = ""
authors = ["Vitalii Bilyk <vitalii.bilyk1@epam.com>"]
readme = "README.md"
keywords = ["ai"]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
aidial-interceptors-sdk = "~=0.4.0"
uvicorn = "^0.34.0"
langfuse = "^2.59.3"
nox = "^2025.2.9"
requests = "^2.32.3"
pydantic = "^2.10.6"

[tool.poetry.group.dev.dependencies]
ipdb = "^0.13.13"

[tool.poetry.group.lint.dependencies]
flake8 = "^7.1.2"
pyright = "^1.1.394"
black = "^25.1.0"
autoflake = "^2.3.1"


[tool.poetry.group.test.dependencies]
pytest = "^8.3.5"
pytest-asyncio = "^0.25.3"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
