image:
  pullPolicy: Always
  registry: registry-dev.deltixhub.com
  repository: ai/dial/application/dial-interceptor-example
  tag: development
  pullSecrets:
    - epm-rtc-registry-dev

fullnameOverride: "dial-interceptor-example"

podAnnotations:
  autorestart: '{{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC" }}'

containerSecurityContext:
  runAsUser: 1001

podSecurityContext:
  fsGroup: 1001

ingress:
  enabled: false

serviceAccount:
  create: true

env:
  DIAL_URL: "http://core.dial-development"
  LOG_LEVEL: "DEBUG"