name: PR Workflow

on:
  pull_request:
    branches: [development, release-*]

jobs:
  run_tests:
    uses: epam/ai-dial-ci/.github/workflows/python_package_pr.yml@d3428a4026de3ddc5e74feea2b3760895ecbb30d
    secrets: inherit
    with:
      python_version: 3.11
      test_python_versions: '["3.11", "3.12"]'
