name: Release Workflow

on:
  push:
    branches: [development, release-*]

jobs:
  release:
    uses: epam/ai-dial-ci/.github/workflows/python_package_release.yml@1.9.0
    secrets: inherit
    with:
      python_version: 3.11
      test_python_versions: '["3.11", "3.12"]'
